### ISSUE TITLE
Error message "Source XY is not available"

### ISSUE THREAD

**Issue by AntonSack** [felixfbecker/vscode-php-debug#31]
Hi Felix, 

I installed the extension as you suggested. When calling the page, the VS debugger is called, so the connection is established. Nevertheless I face the problem, that instead of displaying the php page, an error is displayed: "Source c:/xampp/htdocs/launchpad/index.php is not available.". I fiddled around with the settings for serverSourceRoot and localSourceRoot but the message never changes. I therefore don't understand where this directory comes from.

Log output (I assume that you are looking for these two request / responses, right?):
```js
-> setBreakpointsRequest
{ type: 'request',
  seq: 12,
  command: 'setBreakpoints',
  arguments: 
   { source: { path: '/Users/XXXXX/coreplatformlaunchpad/index.php' },
     lines: [ 3 ],
     breakpoints: [ { line: 3 } ] } }
<- setBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 12,
  command: 'setBreakpoints',
  success: true,
  body: { breakpoints: [ { verified: true, line: 3 } ] } }


-> stackTraceRequest
{ type: 'request',
  seq: 16,
  command: 'stackTrace',
  arguments: { threadId: 2, levels: 20 } }
<- stackTraceResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 16,
  command: 'stackTrace',
  success: true,
  body: 
   { stackFrames: 
      [ StackFrame {
          id: 2,
          source: 
           Source {
             name: 'index.php',
             path: '/C:/xampp/htdocs/launchpad/index.php',
             sourceReference: 0 },
          line: 3,
          column: 1,
          name: '{main}' } ] } }
```

**Comment by felixfbecker** [comment]
Can you please send me your launch.json?

**Comment by AntonSack** [comment]
Hi Felix,

no prob:

{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Listen for XDebug",
			"type": "php",
            "stopOnEntry": true,
			"request": "launch",
			"port": 9000,
            "serverSourceRoot": "c:/xampp/htdocs/launchpad/",
            "localSourceRoot": "/Users/XXXXXX/coreplatformlaunchpad/",
            "log": true
		},
		{
			"name": "Launch currently open script",
			"type": "php",
			"request": "launch",
			"program": "${file}",
			"cwd": "${fileDirname}",
			"port": 9000
		}
	]
}

**Comment by felixfbecker** [comment]
@AntonSack Do you still experience the issue?

**Comment by apit** [comment]
i'm on osx/vs code insiders latest, debugging remote windows server too, and i'm still experience this issue.


```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Devapp XDebug",
            "type": "php",
            "request": "launch",
            "port": 9001,
            "serverSourceRoot": "d:/Y/sisdm-staging/",
            "localSourceRoot": "/Users/X/Projects/bpk/sisdm/sisdm-dev/"
        }
    ]
}

```
error message: `Source /Users/X/Projects/D:/Y/sisdm-staging/surat/riwayat.php is not available.` 
what's with that /Users/X/Projects prefix?

xdebug log: http://pastebin.com/X3UNLdi4

**Comment by felixfbecker** [comment]
@apit @AntonSack Your `serverSourceRoot` uses forward slashes even though you are on Windows, please try to use backward slahes like this:
```json
"serverSourceRoot": "d:\\Y\\sisdm-staging"
```

**Comment by apit** [comment]
@felixfbecker still the same error message

**Comment by felixfbecker** [comment]
I added some unit tests in bfb6a6eea729d1fcba4de877686e4e793dace483 for the path handling and you guys are right, see https://travis-ci.org/felixfbecker/vscode-php-debug/jobs/144964692#L940

**Comment by felixfbecker** [comment]
Should be fixed in 651577cbe7c0beb42b9ecc1b5dc91fd7ef9bef5. Could you please test this release?

[php-debug-1.9.3.vsix.zip](https://github.com/felixfbecker/vscode-php-debug/files/365784/php-debug-1.9.3.vsix.zip)
f

**Comment by apit** [comment]
now sometimes nothing happened, another times timeout like shown below. fiddling with restarting IIS and debugging session to no avail. 

![screenshot_284](https://cloud.githubusercontent.com/assets/98901/16872802/844e8f52-4ab9-11e6-9238-cc9b00e960a2.jpg)

**Comment by felixfbecker** [comment]
That may not be related to my fix... Could you please try to test it out without remote debugging, by simply using the testproject and a Launch as CLI config?

**Comment by felixfbecker** [comment]
I would also recommend you to update your XDebug to 2.4

**Comment by apit** [comment]
back to office... i tried php 5.3/xdebug 2.2.7 (>=2.3 not available for 5.3) and 5.6/2.4 with a simple oneliner project and latest vscode/insiders. localhost/cli works, remote nope.  breakpoint still not triggered although it has been [set](http://pastebin.com/NKF2GJg8)

**Comment by felixfbecker** [comment]
I will try this out when I have more time. I don't have a setup for remote host debugging (and it's not possible to unit-test)

**Comment by felixfbecker** [comment]
[php-debug-1.9.3.vsix.zip](https://github.com/felixfbecker/vscode-php-debug/files/378219/php-debug-1.9.3.vsix.zip)
Does this fix it?

**Comment by apit** [comment]
back to https://github.com/felixfbecker/vscode-php-debug/issues/31#issuecomment-232858225 unfortunately

**Comment by felixfbecker** [comment]
I published 1.9.4 shortly after with another fix. Nice that it is working for you now.
